name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'

permissions:
  contents: read

jobs:
  unit-tests:
    name: Unit Tests (PHP ${{ matrix.php-version }} ${{ matrix.os }})
    
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php-version: [ 8.1, 8.2 ]
        include:
          - coverage: coverage
            os: ubuntu-latest
            php-version: 8.2

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: ${{ matrix.coverage && 'pcov' || 'none' }}
          ini-values: ${{ matrix.coverage && '' || 'opcache.enable_cli=1' }}

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php${{ matrix.php-version }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php-version }}-composer-

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-interaction

      - name: PHPUnit tests
        run: vendor/bin/phpunit ${{ matrix.coverage && '--coverage-clover=coverage.xml --coverage-text --colors' }}

      - name: Upload coverage reports to Codecov
        if: ${{ matrix.coverage }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Disable pcov before psalm
        if: ${{ matrix.coverage }}
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          ini-values: opcache.enable_cli=1

      - name: Psalm coverage
        if: ${{ matrix.coverage }}
        run: vendor/bin/psalm --shepherd