name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'

permissions:
  contents: read

jobs:
  unit-tests:
    name: Unit Tests (PHP ${{ matrix.php-version }} ${{ matrix.os }})
    
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        php-version:
          - "8.1"
          - "8.2"

        experimental:
          - false
          
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php${{ matrix.php-version }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php-version }}-composer-

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-interaction

      - name: PHPUnit tests
        run: vendor/bin/phpunit

  code-coverage:
    name: Code Coverage

    needs:
      - unit-tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: pcov
          tools: phpunit

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php8.2-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php8.2-composer-

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-interaction

      - name: PHPUnit coverage
        run: phpunit --coverage-clover=coverage.xml --coverage-text --colors

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  psalm-coverage:
    name: Psalm Coverage

    needs:
      - unit-tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: psalm

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php8.2-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php8.2-composer-

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-interaction

      - name: Psalm coverage
        run: psalm --shepherd
